[package]
name = "tagger"
version = "1.0.0"
# https://aptos.dev/guides/move-guides/upgrading-move-code/
upgrade_policy = "compatible"
authors = []

[addresses]
tagger = "_"
std = "0x1"
aptos_framework = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
